### ISSUE TITLE
Print duty hours on `who is on duty?` command

### ISSUE THREAD

**Issue by alosenkov-infobip** [mr-exz/whoisondutytoday#100]
Use case.

When somebody asks

```bash
@cibot who is on duty?
```

cibot replies with the duty person name

![image](https://user-images.githubusercontent.com/87190493/169274963-d3c6670e-e4de-452d-922c-95e7cf98c996.png)

But it's also very useful to display current duty hours, both for client transparency and own checking "what duty time do I have now?".

Reply example

```bash
<DUTY_ENGINEER_NAME> on duty today. Duty hours: from XXX to YYY (UTC)
```

**Comment by mr-exz** [comment]
will be available in 0.7.0
