### ISSUE TITLE
Default message

### ISSUE THREAD

**Issue by idemin** [mr-exz/whoisondutytoday#113]
Make it possible to setup default message which bot can reply on each new message in channel.
Currently that is only possible by setting up unreal duty hours like 00:00-00:00 (no duty all day).
in that case bot will send
"You asked at non working hours. Support hours 00:00 - 00:00. Current time is: xx:xx (UTC)." + custom text.
Such message can confuse channel visitors, which could be avoid.

In case of having such "default message" we don't need messages with duty hours, so if such default message set we should switch-off duty hours replies, or just have a separate command to switch them off.

As a result: bot can be configured to reply with default messages and call right duty person without revealing exact person's duty hours, as we need to have possibility to call duty person (troubleshooter) anyway.

**Comment by mr-exz** [comment]
vill be available in 0.7.0 version
