### ISSUE TITLE
known-problem reply feature doesn't trigger if `problem` is in a code block

### ISSUE THREAD

**Issue by alosenkov-infobip** [mr-exz/whoisondutytoday#134]
Hi! Thank you for the great feature with `known-problem` responses! But we faced that if the `problem` part is wrapped with a code block syntax (```), the bot doesn't trigger on it.
This is very nice to have the bot triggered on code block problem appearances too.

Could you, please, check this?

**Comment by mr-exz** [comment]
Implemented in 0.9.0
