### ISSUE TITLE
No `non-working-hours` message if `known-problem` reply triggered

### ISSUE THREAD

**Issue by alosenkov-infobip** [mr-exz/whoisondutytoday#135]
## Case

Someone posted a request to a support channel our of working hours with a `known-problem` pattern.

## Expected behaviour

1. The bot responds with a `known-problem` action message.
2. Then the bot also posts  a`non-working-hours`/`non-working-day` message.

## Actual behaviour

1. The bot responds with the `known-problem` action message only 😔 

The problem is the requester is not notified about non-working hours and they could start a conversation waiting someone to come --> also doesn't know about call duty person to get help

**Comment by mr-exz** [comment]
Implemented in 0.9.0
