### ISSUE TITLE
Provide a feature for the duty person to share bot's action solution with the reporter

### ISSUE THREAD

**Issue by alosenkov-infobip** [mr-exz/whoisondutytoday#169]
Hi!

I'm as a duty person in a channel where bot actions are used, would like to have a feature to find and get the bot's response to share the solution in the channel.

## Current blockers

1. The bot doesn't react on the duty person messages when suggesting actions (and that's good) --> I have to ask the reporter to type `PROBLEM_SUBSTRING` in the thread to get the response.
2. If I don't remember which actions and problem substrings are available.

## Idea

1. Add command like `@bot action list` to print actions available for this channel. Probably a short list of just `problem` field would be enough, i.e. without solution text. I could run this command in my personal thread.

    ```ruby
    # Output example
    [
        "My problem 1",
        "My problem 2",
        "My problem 3"
    ]
    ````

2. Add a command to retrieve the solution for the problem specified, like `@bot action show problem:PROBLEM_SUBSTRING` (syntax similar to `@bot action create` — I would like to call this command in the support channel to share the solution with the reporter.

Thank you in advance for your work! ❤️

**Comment by mr-exz** [comment]
added in 0.18.0
